-- auto Generated on 2018-05-03 11:56:12 
-- DROP TABLE IF EXISTS `test`; 
CREATE TABLE test(
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
    `age` INTEGER(12) NOT NULL DEFAULT -1 COMMENT 'age',
    `name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'name',
    PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT 'test';
